syntax on
filetype plugin indent on

set autoindent
set autoread
set background=dark
let &backupdir = '.,' . $XDG_DATA_HOME . '/nvim/backup'
set belloff=all
set nocompatible
set complete-=i
set cscopeverbose
let &directory = $XDG_DATA_HOME . '/nvim/swap//'
set display="lastline,msgsep"
set encoding=utf-8
set fillchars="vert:│,fold:·"
set formatoptions=tcqj
set nofsync
set history=10000
set hlsearch
set incsearch
set laststatus=2
set listchars="tab:> ,trail:-,nbsp:+"
set nrformats="bin,hex"
set sessionoptions-=options
set shortmess+=F
set shortmess-=S
set showcmd
set sidescroll=1
set smarttab
set tabpagemax=50
set tags="./tags;,tags"
set ttimeoutlen=50
set ttyfast
let &undodir = $XDG_DATA_HOME . '/nvim/undo'
set viminfo+=!
set wildmenu

execute "source " . $XDG_CONFIG_HOME . '/nvim/init.vim'
