#!/bin/bash

set -ev
mkdir -p "$XDG_CACHE_HOME"/bash
mkdir -p "$XDG_CACHE_HOME"/nvim/sessions
mkdir -p "$XDG_CACHE_HOME"/ssh
mkdir -p "$XDG_DATA_HOME"/nvim/undo
mkdir -p "$XDG_DATA_HOME"/nvim/backup
mkdir -p "$XDG_DATA_HOME"/nvim/swap
VIMPACKDIR="$XDG_DATA_HOME"/nvim/site/pack/default
if test ! -d "$VIMPACKDIR"; then
    yadm worktree add -q "$VIMPACKDIR" vimpack
fi
git -C "$VIMPACKDIR" submodule update --init --recursive
VIMPACKDIR=~/.vim/pack/default
if test ! -d "$VIMPACKDIR"; then
    yadm worktree add -q -b vimpack-vim "$VIMPACKDIR" vimpack
fi
git -C "$VIMPACKDIR" submodule update --init --recursive
fish -c 'source ~/.config/fish/init.fish'
