#!/bin/bash

fish -c 'source ~/.config/fish/init.fish'
mkdir -p ~/.vim && ln -fns $XDG_CACHE_HOME/nvim/site/autoload ~/.vim/autoload
mkdir -p $XDG_CACHE_HOME/bash
mkdir -p $XDG_CACHE_HOME/nvim/sessions
mkdir -p $XDG_CACHE_HOME/ssh
vim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
